updated deployment scripts

diff --git a/.github/workflows/generate-and-commit-roles.yml b/.github/workflows/generate-and-commit-roles.yml
--- a/.github/workflows/generate-and-commit-roles.yml
+++ b/.github/workflows/generate-and-commit-roles.yml
@@ -24,6 +24,9 @@ jobs:
 
       - name: "Setup Node"
         uses: "actions/setup-node@v4"
+        with:
+          node-version: "20"
+          cache: "npm"
 
       - name: "Install dependencies"
         run: "npm install"
@@ -39,9 +42,16 @@ jobs:
       - name: "Run generate script to get latest IAM roles"
         run: "npm run generate"
 
+      - name: "Verify file Changes"
+        id: "check_changes"
+        run: |
+          git status
+          echo "---- Verifying changes ----"
+          ls -R src/content/roles || echo "Directory src/content/roles not found"
+
       - name: "Commit updated roles"
         uses: "stefanzweifel/git-auto-commit-action@v5"
         with:
           commit_message: "chore: Auto-update IAM roles from daily cron"
-          branch: "${{ github.ref_name }}" # Commits to the current branch
-          file_pattern: "src/content/roles/**/*.json"
+          commit_user_name: "github-actions[bot]"
+          commit_user_email: "github-actions[bot]@users.noreply.github.com"
